'use strict';

module.exports = {
	"default-3.4": Array.from(require("./default-3.4")),
	"default-3.5": Array.from(require("./default-3.5")),
	"default-3.6": Array.from(require("./default-3.6")),
	"default": Array.from(require("./default")),
	"es5": Array.from(require("./es5")),
	"es6": Array.from(require("./es6")),
	"es7": Array.from(require("./es7")),
	"es2017": Array.from(require("./es2017")),
	"blissfuljs": Array.from(require("./blissfuljs")),
	"modernizr:es6array": ["Array.from", "Array.of", "Array.prototype.@@iterator", "Array.prototype.entries", "Array.prototype.fill", "Array.prototype.find", "Array.prototype.findIndex", "Array.prototype.keys", "Array.prototype.values"],
	"modernizr:es5array": ["Array.isArray", "Array.prototype.every", "Array.prototype.filter", "Array.prototype.forEach", "Array.prototype.indexOf", "Array.prototype.lastIndexOf", "Array.prototype.map", "Array.prototype.reduce", "Array.prototype.reduceRight", "Array.prototype.some"],
	"modernizr:es7array": ["Array.prototype.includes"],
	"caniuse:audio-api": ["AudioContext"],
	"modernizr:webaudio": ["AudioContext"],
	"modernizr:customevent": ["CustomEvent"],
	"modernizr:es5date": ["Date.now", "Date.prototype.toISOString"],
	"modernizr:classlist": ["Element.prototype.classList"],
	"caniuse:matchesselector": ["Element.prototype.matches"],
	"caniuse:input-placeholder": ["Element.prototype.placeholder"],
	"modernizr:placeholder": ["Element.prototype.placeholder"],
	"caniuse:hashchange": ["Event.hashchange"],
	"modernizr:hashchange": ["Event.hashchange"],
	"modernizr:es5function": ["Function.prototype.bind"],
	"caniuse:json": ["JSON"],
	"modernizr:json": ["JSON"],
	"dom4": ["Node.prototype.contains"],
	"modernizr:es6object": ["Object.assign", "Object.is"],
	"modernizr:es5object": ["Object.create", "Object.defineProperties", "Object.defineProperty", "Object.getOwnPropertyDescriptor", "Object.getOwnPropertyNames", "Object.getPrototypeOf", "Object.keys"],
	"modernizr:promises": ["Promise"],
	"caniuse:promises": ["Promise"],
	"modernizr:es6string": ["String.prototype.endsWith", "String.prototype.includes", "String.prototype.repeat", "String.prototype.startsWith"],
	"modernizr:es5string": ["String.prototype.trim"],
	"modernizr:urlparser": ["URL"],
	"caniuse:datauri": ["atob"],
	"caniuse:console-basic": ["console.assert", "console.clear", "console.count", "console.debug", "console.dir", "console.dirxml", "console.error", "console.exception", "console.group", "console.groupCollapsed", "console.groupEnd", "console.info", "console.log", "console.profile", "console.profileEnd", "console.table", "console.time", "console.timeEnd", "console.timeStamp", "console.timeline", "console.timelineEnd", "console.trace", "console.warn", "console"],
	"caniuse:visib": ["document.visibilityState"],
	"caniuse:pagevisibility": ["document.visibilityState"],
	"modernizr:pagevisibility": ["document.visibilityState"],
	"PageVisibility": ["document.visibilityState"],
	"caniuse:namevalue-storage": ["localStorage"],
	"modernizr:localstorage": ["localStorage"],
	"caniuse:matchmedia": ["matchMedia"],
	"modernizr:matchmedia": ["matchMedia"],
	"caniuse:geolocation": ["navigator.geolocation"],
	"modernizr:geolocation": ["navigator.geolocation"],
	"Navigator.prototype.geolocation": ["navigator.geolocation"],
	"caniuse:requestanimationframe": ["requestAnimationFrame"],
	"modernizr:requestanimationframe": ["requestAnimationFrame"],
	"html5shiv": ["~html5-elements"],
	"viewport": ["~viewport"],
	"innerHeight": ["~viewport"],
	"innerWidth": ["~viewport"],
	"pageXOffset": ["~viewport"],
	"pageYOffset": ["~viewport"],
	"scrollX": ["~viewport"],
	"scrollY": ["~viewport"]
};
